import '@/styles/main.scss';
import '@/libs/js/jquery-ui.min';
import '@/components/star-rating';
import '@/components/field';
import '@/components/button-like';
import '@/components/range-slider';
import '@/components/date-picker';
import '@/components/drop-down';
import '@/components/check-box-list';
