import '@/pug/utils/jquery-ui.min';
import '@/assets/css/main.scss';
import '@/pug/components/star-rate/star-rate';
import '@/pug/components/input/input';
import '@/pug/components/like-button/like-button';
import '@/pug/components/range-slider/range-slider';
import '@/pug/components/data-select/data-select';
import '@/pug/components/drop-down/drop-down';
import '@/pug/components/check-box/check-box';
